app = "ta-iad-cursed"
primary_region = "iad"
kill_timeout = "5s"
kill_signal = "SIGHUP"


[http_service]
  internal_port = 8008
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "1s"
    method = "GET"
    path = "/"
  [http_service.concurrency]
  soft_limit = 100
  hard_limit = 1000
